sudo: false

language: python

python:
  - 2.7
  - 3.5

install:
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - py.test --cov=vnchart/

after_success:
  - bash <(curl -s https://codecov.io/bash)